export const subjects = [
    "🌍 Geography",
    "🧪 Science",
    "🎵 Music",
    "🎬 Movies",
    "📚 Literature",
    "⚽ Sports",
    "🏛️ History",
    "💻 Technology",
    "🍳 Food",
    "🧩 Puzzles",
    "🎮 Video Games",
    "🖼️ Art",
    "🚀 Space",
    "🐾 Animals",
    "🧑‍🎤 Celebrities",
    "📺 TV Shows",
    "🏞️ Nature",
    "💡 General Knowledge",
    "💰 Business & Economy",
    "🗳️ Politic",
];
